name: FineTuneQwen14b
channels:
  - defaults
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=7_kmp_llvm
  - _python_abi3_support=1.0=hd8ed1ab_2
  - accelerate=1.12.0=pyhcf101f3_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.3=py310h31b6992_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - altair=6.0.0=pyhd8ed1ab_1
  - anyio=4.12.1=pyhcf101f3_0
  - aom=3.12.1=h7934f7d_0
  - async-timeout=5.0.1=pyhcf101f3_2
  - attr=2.5.2=h39aace5_0
  - attrs=25.4.0=pyhcf101f3_1
  - aws-c-auth=0.9.1=h4168de2_1
  - aws-c-cal=0.9.2=he7b75e1_1
  - aws-c-common=0.12.4=hb03c661_0
  - aws-c-compression=0.3.1=h92c474e_6
  - aws-c-event-stream=0.5.6=h4d13e43_1
  - aws-c-http=0.10.4=hbd4fbc6_1
  - aws-c-io=0.21.4=h88603f0_1
  - aws-c-mqtt=0.13.3=h680d5b3_4
  - aws-c-s3=0.8.6=h2635518_3
  - aws-c-sdkutils=0.2.4=h92c474e_1
  - aws-checksums=0.2.7=h92c474e_2
  - aws-crt-cpp=0.34.1=h317f721_1
  - aws-sdk-cpp=1.11.606=hb61a61c_2
  - azure-core-cpp=1.16.0=h3a458e0_1
  - azure-identity-cpp=1.12.0=ha729027_0
  - azure-storage-blobs-cpp=12.14.0=hb1c9500_1
  - azure-storage-common-cpp=12.10.0=hebae86a_2
  - azure-storage-files-datalake-cpp=12.12.0=h8b27e44_3
  - binutils_impl_linux-64=2.44=h4b9a079_2
  - bitsandbytes=0.49.1=cpu_py310h91ab2ec_0
  - blas=2.305=openblas
  - blas-devel=3.11.0=5_h1ea3ea9_openblas
  - blinker=1.9.0=pyhff2d567_0
  - brotlicffi=1.2.0.0=py310h7354ed3_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cachetools=6.2.4=pyhd8ed1ab_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2026.01.04=py310h06a4308_0
  - cffi=2.0.0=py310h4eded50_1
  - charset-normalizer=3.4.4=py310h06a4308_0
  - click=8.3.1=pyh8f84b5b_1
  - cmake=4.2.1=hc85cc9f_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - conda-gcc-specs=15.2.0=h53410ce_16
  - cpython=3.10.19=py310hd8ed1ab_2
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.9.19=h5888daf_0
  - cuda-runtime=12.1.0=0
  - cuda-version=12.9=h4f385c5_3
  - datasets=4.4.2=pyhcf101f3_0
  - dav1d=1.2.1=h5eee18b_0
  - dill=0.4.0=pyhcf101f3_1
  - distro=1.9.0=py310h06a4308_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - expat=2.7.3=h7354ed3_4
  - ffmpeg=4.2.2=h20bf706_0
  - fontconfig=2.15.0=h2c49b7f_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.16=h9fb5f84_0
  - frozenlist=1.7.0=py310h9548a50_0
  - fsspec=2025.10.0=pyhd8ed1ab_0
  - gcc=15.2.0=hc115cf6_7
  - gcc_impl_linux-64=15.2.0=hcacfade_7
  - gflags=2.2.2=h5888daf_1005
  - giflib=5.2.2=h5eee18b_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.46=pyhd8ed1ab_0
  - glog=0.7.1=hbabe93e_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.2=py310ha78e65c_0
  - gnutls=3.6.15=he1e5248_0
  - graphite2=1.3.14=h295c915_1
  - gxx=15.2.0=h834e499_7
  - gxx_impl_linux-64=15.2.0=h54ccb8d_7
  - h11=0.16.0=pyhcf101f3_1
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=10.2.0=hdfddeaa_1
  - hf-xet=1.2.1=py310hb823017_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - huggingface_hub=0.36.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.11=py310h06a4308_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2025.0.0=h06a4308_1171
  - jinja2=3.1.6=py310h06a4308_0
  - jiter=0.12.0=py310h498d7c9_0
  - jpeg=9f=h5ce9db8_0
  - jsonschema=4.26.0=pyhcf101f3_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - kaldi=5.5.1112=cuda120h41cae9c_1
  - kernel-headers_linux-64=6.12.0=he073ed8_5
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.17=heab6991_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250512.1=cxx17_hba17884_0
  - libarrow=21.0.0=hd51ebda_4_cpu
  - libarrow-acero=21.0.0=h635bf11_4_cpu
  - libarrow-compute=21.0.0=h8c2c5c3_4_cpu
  - libarrow-dataset=21.0.0=h635bf11_4_cpu
  - libarrow-substrait=21.0.0=h3f74fd7_4_cpu
  - libavif=1.3.0=h3539ee5_0
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcap=2.77=h3ff7636_0
  - libcblas=3.11.0=5_h0358290_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.14.1.1=hbc026e6_1
  - libcurand=10.3.10.19=h676940d_1
  - libcurl=8.18.0=h4e3cde8_0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-devel_linux-64=15.2.0=h73f6952_107
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran-ng=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libglib=2.84.4=h1fb398f_1
  - libgomp=15.2.0=h4751f2c_7
  - libgoogle-cloud=2.39.0=hdb79228_0
  - libgoogle-cloud-storage=2.39.0=hdbdcf42_0
  - libgrpc=1.73.1=h3288cfb_1
  - libhwloc=2.12.1=default_hf1bbc79_1000
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblapacke=3.11.0=5_h6ae95b6_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libmagma=2.7.2=h173bb3b_2
  - libmagma_sparse=2.7.2=h173bb3b_3
  - libnghttp2=1.67.0=had1ee68_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnpp=12.0.2.50=0
  - libnsl=2.0.0=h5eee18b_0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libopenblas=0.3.30=openmp_hd680484_2
  - libopenjpeg=2.5.4=hee96239_1
  - libopentelemetry-cpp=1.21.0=hb9b0907_1
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_1
  - libopus=1.3.1=h5eee18b_1
  - libparquet=21.0.0=h790f06f_4_cpu
  - libpng=1.6.50=h2ed474d_0
  - libprotobuf=6.31.1=h49aed37_4
  - libre2-11=2025.11.05=h7b12aa8_0
  - libsanitizer=15.2.0=hb13aed2_7
  - libsentencepiece=0.2.1=h1d72405_1
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-devel_linux-64=15.2.0=h73f6952_107
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libsystemd0=258.3=h6569c3e_0
  - libtasn1=4.21.0=h27ab2c4_0
  - libthrift=0.22.0=h454ac66_1
  - libtiff=4.7.1=h029b1ac_0
  - libtorch=2.7.1=cpu_generic_h1322af4_3
  - libudev1=258.3=h6569c3e_0
  - libunistring=0.9.10=h27cfd23_0
  - libutf8proc=2.11.2=hfe17d71_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.51.0=hb03c661_1
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.6.0=h089d785_0
  - libwebp-base=1.6.0=hb7bb969_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvm-openmp=20.1.8=h4922eb0_0
  - lz4-c=1.10.0=h5888daf_1
  - magma=2.7.2=h51420fd_3
  - markupsafe=3.0.2=py310h5eee18b_0
  - mkl=2024.2.2=ha770c72_17
  - mkl-service=2.5.2=py310h2e2cc33_1
  - mkl_fft=2.0.0=py310had43185_1
  - mkl_random=1.2.11=py310hcacb51e_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py310h06a4308_0
  - multidict=6.7.0=py310h3406613_0
  - multiprocess=0.70.18=py310h139afa4_2
  - narwhals=2.15.0=pyhcf101f3_0
  - ncurses=6.5=h7934f7d_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.4.2=py310h06a4308_0
  - ninja=1.13.2=h171cf75_0
  - nlohmann_json=3.12.0=h54a6638_1
  - nomkl=3.0=0
  - ocl-icd=2.3.3=h47b2149_0
  - openai=2.14.0=py310h06a4308_0
  - openblas=0.3.30=openmp_hd77311e_2
  - opencl-headers=2025.07.22=hfb20e49_0
  - openfst=1.8.3=h84d6215_3
  - openh264=2.1.1=h4ff587b_0
  - openssl=3.6.0=h26f9b46_0
  - optree=0.18.0=py310h03d9f68_0
  - orc=2.2.0=h1bc01a4_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py310h0158d43_2
  - pcre2=10.46=hf426167_0
  - peft=0.18.1=pyhcf101f3_0
  - pillow=12.0.0=py310h3b88751_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - prometheus-cpp=1.3.0=ha5d0236_0
  - propcache=0.3.1=py310h89163eb_0
  - protobuf=6.31.1=py310ha36e12e_2
  - psutil=7.2.1=py310h139afa4_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pyarrow=21.0.0=py310hff52083_1
  - pyarrow-core=21.0.0=py310h923f568_1_cpu
  - pybind11=3.0.1=pyh7a1b43c_0
  - pybind11-global=3.0.1=pyhc7ab6ef_0
  - pycparser=2.23=py310h06a4308_0
  - pydantic-core=2.41.5=py310h498d7c9_1
  - pydeck=0.9.1=pyhd8ed1ab_0
  - pysocks=1.7.1=py310h06a4308_1
  - python=3.10.19=h6fa692b_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.10.19=hd8ed1ab_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python-xxhash=3.6.0=py310hf3bd8b6_1
  - python_abi=3.10=2_cp310
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py310h591646f_0
  - rdma-core=60.0=hecca717_0
  - re2=2025.11.05=h5301d42_0
  - readline=8.3=hc2a1206_0
  - referencing=0.37.0=pyhcf101f3_0
  - regex=2026.1.15=py310h7c4b9e2_0
  - requests=2.32.5=py310h06a4308_1
  - rhash=1.4.6=hb9d3cd8_1
  - rpds-py=0.30.0=py310hd8f68c5_0
  - s2n=1.5.25=h5ac9029_1
  - safetensors=0.7.0=py310hdfeec95_0
  - scipy=1.15.2=py310h1d65ade_0
  - sentencepiece=0.2.1=hc5512b6_1
  - sentencepiece-python=0.2.1=py310h1469a80_1
  - sentencepiece-spm=0.2.1=h1d72405_1
  - setuptools=80.9.0=py310h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=ha0421bc_0
  - smmap=5.0.2=pyhd8ed1ab_0
  - snappy=1.2.2=h03e3b7b_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - sqlite=3.51.1=he0a8d7e_0
  - streamlit=1.53.0=pyhd8ed1ab_0
  - sysroot_linux-64=2.39=hc4b9eeb_5
  - tbb=2021.13.0=h8d10470_4
  - tbb-devel=2021.13.0=h74b38a2_4
  - tenacity=9.1.2=pyhd8ed1ab_0
  - tk=8.6.15=h54e0aa7_0
  - tokenizers=0.22.2=py310h4551fc8_0
  - toml=0.10.2=pyhcf101f3_3
  - tornado=6.5.4=py310ha78b2d2_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - transformers=4.57.5=pyhd8ed1ab_0
  - typing-extensions=4.15.0=py310h06a4308_0
  - typing-inspection=0.4.2=py310h06a4308_0
  - typing_extensions=4.15.0=py310h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.6.3=py310h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - watchdog=6.0.0=py310hff52083_2
  - wheel=0.45.1=py310h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xxhash=0.8.3=hb47aa4a_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.22.0=py310h3406613_0
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - absl-py==2.3.1
      - aiohttp-cors==0.8.1
      - aiosqlite==0.22.1
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - ase-db-backends==0.11.0
      - asyncio==4.0.0
      - cloudpickle==3.1.2
      - clusterscope==0.0.18
      - colorful==0.5.8
      - contourpy==1.3.2
      - cryptography==46.0.3
      - cycler==0.12.1
      - diskcache==5.6.3
      - distlib==0.4.0
      - e3nn==0.5.9
      - fastapi==0.128.0
      - filelock==3.20.3
      - fonttools==4.61.1
      - gguf==0.17.1
      - google-api-core==2.29.0
      - google-auth==2.47.0
      - googleapis-common-protos==1.72.0
      - greenlet==3.3.1
      - grpcio==1.76.0
      - httptools==0.7.1
      - hydra-core==1.3.2
      - kiwisolver==1.4.9
      - llama-cpp-python==0.3.16
      - llvmlite==0.46.0
      - markdown==3.10
      - matplotlib==3.10.8
      - monty==2025.3.3
      - msgpack==1.1.2
      - mypy-extensions==1.1.0
      - numba==0.63.1
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opentelemetry-api==1.39.1
      - opentelemetry-exporter-prometheus==0.60b1
      - opentelemetry-proto==1.39.1
      - opentelemetry-sdk==1.39.1
      - opentelemetry-semantic-conventions==0.60b1
      - opt-einsum==3.4.0
      - opt-einsum-fx==0.1.4
      - orjson==3.11.5
      - platformdirs==4.5.1
      - prometheus-client==0.24.1
      - proto-plus==1.27.0
      - psycopg2-binary==2.9.11
      - py-spy==0.4.1
      - pyasn1==0.6.2
      - pyasn1-modules==0.4.2
      - pydantic==2.12.5
      - pymysql==1.1.2
      - pyparsing==3.3.1
      - pyre-extensions==0.0.32
      - python-dotenv==1.2.1
      - python-multipart==0.0.22
      - ray==2.53.0
      - rsa==4.9.1
      - ruamel-yaml==0.19.1
      - sentry-sdk==2.49.0
      - smart-open==7.5.0
      - sqlalchemy==2.0.46
      - starlette==0.50.0
      - submitit==1.5.4
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchtnt==0.2.4
      - torchvision==0.20.1+cu121
      - triton==3.1.0
      - trl==0.27.0
      - typing-inspect==0.9.0
      - uvicorn==0.40.0
      - uvloop==0.22.1
      - virtualenv==20.36.1
      - wandb==0.24.0
      - watchfiles==1.1.1
      - websockets==16.0
      - werkzeug==3.1.5
      - wrapt==2.0.1
prefix: /home/kylan/miniconda3/envs/FineTuneQwen14b
